MACHINE Test
//INCLUDE "inc/Test02.bs";
ATTRIBUTES
	#define PI 3.14159
	#define ONE_CIR 2 * PI
	#define HALF_CIR PI
	#define DEG_PI 180

	int global_int;
	const int pi = HALF_CIR;
OPERATIONS
	double deg_to_reg(double in_value)
	{
		double return_result;
		return_result = in_value / DEG_PI;
		return_result = returen_result * HALF_CIR;
		return return_result;
	}
	
	void main(){
		printf(deg_to_reg(3.14159));
	}
END